[build]
  base = ""
  publish = "_site"  # change this if needed, e.g. to "build" for React
  command = "bundle exec jekyll build"

  [build.environment]
    NODE_VERSION = "18"
    PYTHON_VERSION = "3.10.12"
    NETLIFY_USE_NOBLE = "false"

[functions]
  node_bundler = "esbuild"
